// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://xwgcqfoiwtdcadanamcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3Z2NxZm9pd3RkY2FkYW5hbWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDE0ODUsImV4cCI6MjA2MzMxNzQ4NX0.I_3QydAc5UizVOi9s7tj1rc_AXH8SEXNkqtH5jeTZxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);